export const CHOOSE_DELIVERY_METHOD = "CHOOSE_DELIVERY_METHOD";
export const CHOOSE_PAYMENT_METHOD = "CHOOSE_PAYMENT_METHOD";
export const CHOOSE_PICKUP_TIME = "CHOOSE_PICKUP_TIME";
export const ADD_BEER_TO_CART = "ADD_BEER_TO_CART";
export const ADD_RECYCLED_BOOTLE_TO_CART = "ADD_RECYCLED_BOOTLE_TO_CART";
export const INPUT_ADRESS = "INPUT_ADRESS";
